<?php
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/db.php';

$message = "";

/* =========================
   FETCH PROFESSORS
========================= */
$stmt = $pdo->query("SELECT id, name FROM professors ORDER BY name ASC");
$professors = $stmt->fetchAll();

/* =========================
   HANDLE FORM SUBMIT
========================= */
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    $title = trim($_POST['title'] ?? '');
    $date = $_POST['date'] ?? '';
    $professor_id = $_POST['professor_id'] ?? '';
    
    // Check if title, date, and professor are provided
    if ($title && $date && $professor_id) {
        
        $fileNameToStore = "";

        // Handle the File Upload
        if (isset($_FILES['pdf_file']) && $_FILES['pdf_file']['error'] === UPLOAD_ERR_OK) {
            
            $uploadDir = __DIR__ . '/../../uploads/';
            
            // Ensure directory exists
            if (!is_dir($uploadDir)) {
                mkdir($uploadDir, 0777, true);
            }

            $originalName = basename($_FILES['pdf_file']['name']);
            $extension = strtolower(pathinfo($originalName, PATHINFO_EXTENSION));

            if ($extension === 'pdf') {
                // Sanitize and create a unique name to prevent overwriting
                $fileNameToStore = time() . '_' . preg_replace("/[^a-zA-Z0-9.]/", "_", $originalName);
                $destination = $uploadDir . $fileNameToStore;

                if (!move_uploaded_file($_FILES['pdf_file']['tmp_name'], $destination)) {
                    $message = "Error: Failed to save the file to the server.";
                }
            } else {
                $message = "Error: Only PDF files are allowed.";
            }
        }

        // Proceed to DB if no error message was generated by the file logic
        if (empty($message)) {
            $stmt = $pdo->prepare("
                INSERT INTO articles (professor_id, title, date, content)
                VALUES (?, ?, ?, ?)
            ");

            $stmt->execute([
                $professor_id,
                $title,
                $date,
                $fileNameToStore // We store the path/filename in the 'content' column
            ]);

            $message = "Article created successfully with PDF.";
            // Reset POST data so form clears
            $_POST = array(); 
        }

    } else {
        $message = "Please fill all required fields.";
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Article</title>
    <link rel="stylesheet" href="../../style.css">
</head>
<body>

<?php include '../../header.php'; ?>

<div class="container">
    <div class="card" style="max-width: 700px; margin: auto;">

        <h1>Create New Article</h1>

        <?php if ($message): ?>
            <p style="margin-bottom:15px; color: <?= strpos($message, 'Error') !== false ? 'red' : 'green' ?>;">
                <?= htmlspecialchars($message) ?>
            </p>
        <?php endif; ?>

        <form method="POST" enctype="multipart/form-data">

            <label>Title *</label><br>
            <input type="text" name="title" required style="width:100%; padding:8px; margin-bottom:15px;"
                   value="<?= htmlspecialchars($_POST['title'] ?? '') ?>">

            <label>Professor *</label><br>
            <select name="professor_id" required style="width:100%; padding:8px; margin-bottom:15px;">
                <option value="">Select Professor</option>
                <?php foreach ($professors as $prof): ?>
                    <option value="<?= $prof['id'] ?>" <?= (($_POST['professor_id'] ?? '') == $prof['id']) ? 'selected' : '' ?>>
                        <?= htmlspecialchars($prof['name']) ?>
                    </option>
                <?php endforeach; ?>
            </select>

            <label>Date *</label><br>
            <input type="date" name="date" required style="width:100%; padding:8px; margin-bottom:15px;"
                   value="<?= htmlspecialchars($_POST['date'] ?? '') ?>">

            <label>Upload PDF Document *</label><br>
            <input type="file" name="pdf_file" accept=".pdf" required
                   style="width:100%; padding:8px; margin-bottom:20px; border: 1px solid #ccc;">

            <button type="submit" style="padding:10px 20px; cursor: pointer;">
                Publish Article
            </button>

        </form>
        <br>
        <a href="index.php" class="button">&larr; Back to Articles</a>

    </div>
</div>

<?php include '../../footer.php'; ?>

</body>
</html>
